### PR TITLE
Added support for firefox multi-containers

### PR DESCRIPTION
**Pull request by T00mm**
#755 I have implemented the Firefox Container option that works with

https://addons.mozilla.org/en-GB/firefox/addon/multi-account-containers/
https://addons.mozilla.org/en-GB/firefox/addon/open-url-in-container

I completely understand if you got the feeling that this should not merge as this is too dependent on multiple addons and one specific browser.

I have created a small preview of what it does

https://user-images.githubusercontent.com/3200970/111841619-88048380-88fe-11eb-8a1c-a536deb24f1c.mp4

### CODE REVIEW

**Comment by mtibben** [comment]
Yeah this is getting too specific - use the `--stdout` flag and write a shell alias to achieve the same

**Comment by T00mm** [comment]
With only stdout this can't work as stdout doesn't provide a profile name. Is there a plugin system somewhere on the roadmap as I agree with that this is too specific use-case.

**Comment by mtibben** [comment]
something like this bash function would work on macos. Not too sure how to powershell on windows
```bash
awslogin() {
  firefox "$(printf ext+container:name=%s\&url=%s $1 $(aws-vault login --stdout $1))"
}
```

**Comment by awilkins** [comment]
This extension wants the `&` in the extension-url for itself, so you need to urlencode the login URL for this to work.

I've used `jq` here because every AWS power user needs `jq`, right?

```sh
aws-login() {
    firefox "$(printf 'ext+container:name=%s&url=%s' $1 $(aws-vault login --stdout $1 | jq -sRr @uri))"
}
```

**Pull request closed without merging**
