### PR TITLE
Add service option initially implemented by @maishsk

### PR DESCRIPTION
**Pull request by frezbo**
This is a feature enhance to #278 by @maishsk. Thanks a lot for the idea. I tested this both in commercial and gov-cloud region and seems to work like a charm. This also takes cares of the region issue as per #285 .

### CODE REVIEW

**Comment by mtibben** [comment]
Seems like most, but not all, AWS services have the URL form `https://{host}/{service}/home`, though `/{service}` seems to redirect

Is `--service` right here, or would something like `--url-path` be clearer about what this is for? It's possible to deep link into a particular URL in aws web console using this flag too, which `service` doesn't capture

**Comment by frezbo** [comment]
@mtibben so you want `service` along woth `--url-path` for nested services. BTW nice idea. I will try to see if I can spend some time on this.

**Comment by mtibben** [comment]
I was thinking just `--url-path`?

**Comment by maishsk** [comment]
👍 
LGTM

**Pull request merged**
