### PR TITLE
Added support to pass aliases as commands in non windows environments.

### PR DESCRIPTION
**Pull request by tpreecesh**
Hi guys, we have  a need to use aliases as commands and I have changed the cli/exec.go execSyscall function to allow this.

### CODE REVIEW

**Comment by mtibben** [comment]
Do you mean like a bash alias? Can you can pass the full shell command to `exec` to achieve this?

Always executing via the shell feels like it may create a ton of edge-cases. Perhaps an aws-vault wrapper script could achieve this also.

**Comment by georgekaz** [comment]
Yes it means shell aliases, for example, if you have `alias tfplan=terraform plan`, you can successfully execute `aws-vault exec my-profile terraform plan` but cannot execute `aws-vault exec my-profile tfplan`, at least that's what I experienced with zsh.
`aws-vault: error: exec: Couldn't find the executable 'tfplan': exec: "tfplan": executable file not found in $PATH`

**Comment by mtibben** [comment]
Right but I imagine you can `aws-vault exec my-profile -- bash -c 'tfplan'`?

AWS Vault can't inject environment variables directly into your existing shell, so you can also start an interactive shell and then execute... i.e

```shell
$ aws-vault exec my-profile # starts a subshell with AWS env vars
$ tfplan
```

**Comment by georgekaz** [comment]
Yes, `aws-vault exec my-profile -- bash -c 'tfplan'` does work so that's an alternative, and I didn't realise you could start a subshell using `aws-vault exec my-profile` so we can use that info, thanks. 

As it turns out, because this process will be containerised, it's more suitable to for us to use https://github.com/benkehoe/aws-sso-credential-process as described here: https://www.cloudgardener.dev/how-to-use-aws-developer-tools-with-aws-sso/ because it doesn't rely on a local keystore.

Thanks

**Pull request closed without merging**
