### PR TITLE
Allow running just server

### PR DESCRIPTION
**Pull request by astanciu**
Allows running just 
`aws-vault exec --server [PROFILE]`

 without spawning a new shell, waits for ctrl-c to end. In reference to #222

### CODE REVIEW

**Comment by lox** [comment]
Thanks @astanciu! Unfortunately this would be a breaking change, without a command `aws-vault exec [PROFILE]` should execute `$SHELL`. Special casing this for `--server` would be unexpected I reckon.

One approach to this would be to add a `--server-only` argument that did what you have implemented here. 

Beyond that, we should just figure out why the process doesn't cleanly die on suspend.

**Comment by lox** [comment]
>To me aws-vault exec means “execute this command” and aws-vault exec --server means “execute this command with a credential server available to it”. Then the assumption is the credential server ends when the command ends.

Me too, funnily enough.

**Comment by astanciu** [comment]
>  “run a credential server available to the whole system until the user tells it to stop”

This is exactly the desired feature here, and I fully agree with the "exec" semantics. Using --server-only, or updating what `aws-vault server` do seem like more reasonable options (the latter of which makes most sense).

**Comment by lox** [comment]
Ok, let's aim to update `aws-vault server` so that it can run on it's own, and perhaps make the current behaviour something like `aws-vault server --bind-only`?

The only complication is that we need sudo for that port bind.

**Pull request closed without merging**
