### PR TITLE
login endpoints for region

### PR DESCRIPTION
**Pull request by frezbo**
This PR does the following:
    
- Fixes: https://github.com/99designs/aws-vault/issues/258
- Pulls in changes from: https://github.com/99designs/aws-vault/pull/259 and addressed the PR comments
- Pass the region to the client
- Fix a failing `go vet`

Special thanks to @sprice-janrain
    
Signed-off-by: Noel Georgi <git@frezbo.com>

### CODE REVIEW

**Comment by frezbo** [comment]
@lox PTAL

**Comment by aboutte** [comment]
👍

**Comment by frezbo** [comment]
@mtibben can this be merged?

**Comment by lox** [comment]
Yup, seems legit to me.

**Comment by lox** [comment]
Thanks for the contribution @frezbo.

**Pull request merged**
