### PR TITLE
Add support for Yubikey

### PR DESCRIPTION
**Pull request by mtibben**
Adds Yubikey integration, #230.

Yubikey support was originally merged in #316 but was rolled back as the introduction of CGO prevents cross-compilation. This PR will attempt to address that issue

/cc @j0hnsmith

### CODE REVIEW

**Comment by mtibben** [comment]
@j0hnsmith the use of the github.com/ebfe/scard cgo dependency is problematic. Can we reimplement using a native go client?

**Comment by mtibben** [comment]
Seem to be a few native clients here https://godoc.org/?q=pcsc

**Comment by mtibben** [comment]
See here for the ykoath PR https://github.com/yawn/ykoath/pull/9

**Comment by mtibben** [comment]
Could someone with a Yubikey please test this branch?

**Comment by j0hnsmith** [comment]
All the pcsc libraries are wrappers around the C api. 

I think it's going to come down to either figuring out how to build with `CGO=1` (maybe windows and linux on travis, osx on whatever machine you use now as you need the cert right?) or don't merge this feature. Maybe it could be kept in a branch that people have to build themselves if they want it?

**Comment by jonhadfield** [comment]
I've tried with https://github.com/99designs/aws-vault/commit/d1662449236ba155cbaca40cbc3640bb9bef37fc but enabled CGO in the Makefile as it otherwise drops support for the keychain backend. 
After successfully adding the profile using aws-vault, this was my attempt at adding a yubikey:
```
$ ./aws-vault add-yubikey test-aws-vault-yubikey test-aws-vault-yubikey --touch
Adding yubikey to user test-aws-vault-yubikey using profile test-aws-vault-yubikey
aws-vault: error: error registering yubikey
%!(EXTRA *errors.withStack=failed to initialize Yubikey: failed to establish context: dial unix: missing address)
```

**Comment by j0hnsmith** [comment]
@jonhadfield this branch doesn't work, this should work though https://github.com/j0hnsmith/aws-vault/tree/feature/add_yubikey

**Comment by xocasdashdash** [comment]
I've created #426 as a workaround this issue using a completely different way of working with a yubikey. I'd love if people could check it out and see if there was something to improve

**Comment by Klohto** [comment]
Is there any way I could help with this? :angel: 
The workaround is nice, but I would welcome a fully implemented solution

**Comment by j0hnsmith** [comment]
I'm going to fork this repo, build with this functionality and provide a mac only release, I don't have a certificate from apple so there will be a warning upon install. I'll also provide instructions how to build yourself so you don't have to trust that I haven't added anything dodgy.

**Comment by mtibben** [comment]
If the functionality is mac-only then a PR will be welcome. The blocker here was that I don't have a Yubikey and couldn't get cross compilation working

**Comment by j0hnsmith** [comment]
My fork won't solve the cross compilation problem, it will use CGO as before, I'm going to release for mac only initially as that's the machine I use. I might try a linux build at a later stage. 

I've rebased against master so shouldn't be too long.

**Comment by j0hnsmith** [comment]
I was hoping to provide a binary but can't since I don't have an apple developer account therefore keychain will generate too many prompts for it to be practical. If anyone has a way, do let me know.

I've rebased against master and added a little documentation, I'll try to keep the branch up to date. This seems to be the best I can do for now https://github.com/j0hnsmith/aws-vault#aws-vault.

**Comment by j0hnsmith** [comment]
@mtibben I've got it working with build tags 🎉 , Yubikey commands are included only in `darwin` builds (still requires `CGO` though). Is that something that could work with the github workflow build and the release build process?

**Comment by mtibben** [comment]
Closed in favour of #514

**Pull request closed without merging**
