### PR TITLE
Clarify credentials, sessions and profiles

### LINKED ISSUE #137: What should `aws-vault list` show?
Currently `aws-vault list` will show all keys in the aws-vault keychain. This includes sessions. 

I've been thinking of breaking out: `aws-vault list-profiles`, `aws-vault list-sessions` and then have `aws-vault list` show only the credentials that are stored. The alternative would be to have `aws-vault list` have a `--profiles` and `--session` flag. 

Feels?

### PR DESCRIPTION
**Pull request by lox**
Closes #137. Relates to #160.

General cleanup of profile / config parsing code. Implements the `list` command with tabular output:

```
Profile                   Credentials              Sessions
=======                   ===========              ========
ljd                       ljd                      61343032633337323134, 32663735326133373631, 61633665646639303539
ljd-admin                 ljd                      61343032633337323134, 32663735326133373631, 61633665646639303539
xyz                       ljd                      61343032633337323134, 32663735326133373631, 61633665646639303539
```

This of course begs the question, why do we have so many old sessions hanging around?

### CODE REVIEW

**Comment by mtibben** [comment]
So if I understand correctly - Profile is what's in config, Credentials is the ID for the credentials aws-vault uses to generate the session, and will correspond to the `profile` name or the `source_profile` if that's being used

It seems the challenge is working out the right UI to disambiguate between profiles/credentials and make users aware of this nuance, so this is definitely an improvement on what we currently have.

So because it seems this command is using profiles as it's main starting point, does this command list all profiles in config, or just profiles we have credentials stored for?

**Comment by mtibben** [comment]
Ha I just realised you asked the same question https://github.com/99designs/aws-vault/issues/137#issuecomment-331605356

**Comment by lox** [comment]
Yeah, I decided c) all of the above. It will show profiles in your config and it will show credentials without a profile in the config. The only thing it won't do is show sessions that don't have a config entry.

**Comment by lox** [comment]
I'm going to automatically add a config entry with the `add` command to keep things consistent.

**Pull request merged**
