### PR TITLE
Fixed regression that prompted for keychain access for sessions

### PR DESCRIPTION
**Pull request by lox**
I noticed that we were back to displaying three prompts for every access, even when there is a session. Should only prompt once now and not at all if there is an active session.

### CODE REVIEW

**Comment by pda** [comment]
Any idea which commit/PR the regression came in?
Either I haven't experienced it, or I've grown used to it; on `v3.7.1-11-g6dea313`

**Comment by lox** [comment]
I actually think it's been there forever. Try clearing your sessions and running:

```
aws-vault exec my-profile-with-mfa -- time
aws-vault exec my-profile-with-mfa -- time
```

You should get exactly 1 Keychain prompt the first time, and one MFA prompt the second time.

**Comment by pda** [comment]
With v3.7.1-11-g6dea313:

* First command
    * keychain password prompt
    * keychain “allow” button prompt (I never click “always allow”)
    * MFA prompt
* Second command
    * keychain “allow” button prompt

With `v3.7.1-36-g6fcd647` (current master):

* First command
    * keychain “allow prompt”
    * MFA prompt
* Second command
    * *(nothing)*

I guess I had just grown accustomed to all the extra button prompts, and hitting spacebar to “allow”. Nice improvement (as long as it's not harming the security model…?)

**Comment by lox** [comment]
My view is that it's basically the design of sessions. I'd always intended subsequent calls to a session to work without a prompt.

**Comment by pda** [comment]
In my mind, sessions primarily avoid repeated MFA, and keychain unlock/auto-lock time avoid repeated password entry, and both are worthwhile security/usability trade-offs.

Within a session, clicking (or pressing spacebar) to allow each `aws-vault exec …` command is a price I'm happy to pay to know that background processes (e.g. malicious npm modules) can't invisibly obtain AWS credentials.

I'd lean towards keeping that behaviour. And I guess people can and will click Always Allow if they want to make that further security/usability trade-off.

I wonder how this question maps to non-macOS backends.

**Comment by lox** [comment]
I shouldn't have done this, but this PR also included some fixes for the go-keychain stuff: https://github.com/99designs/aws-vault/pull/138/commits/4868b434f590a42a321da7a3e657be651a101190

And it also dropped support for reading credentials from env and shared credentials files, which merited it's own PR too https://github.com/99designs/aws-vault/pull/138/commits/d84f6636db253a52f9b273170b103538e782da32

I regret this now.

**Comment by lox** [comment]
#140 is part of this.

**Comment by lox** [comment]
As is #141.

**Comment by lox** [comment]
And #142. I feel much better now.

**Pull request merged**
