### PR TITLE
searching for legacy keychain if not specified

### PR DESCRIPTION
**Pull request by heph**
if the keychain isn't specified, searches for `aws-vault` followed by `login` to support legacy installations while pushing new users towards the login keychain.

### CODE REVIEW

**Comment by heph** [comment]
@lox plx review

**Comment by lox** [comment]
Neat! I'm just in the process of trying to get my latest few PR's merged in, Travis is giving me all sorts of problems. Let me settle them in and then I'll provide some feedback.

**Comment by lox** [comment]
@heph given we've gone back to defaulting to aws-vault and letting people opt-in to a new vault, I reckon we might hold off on this check until we change the default. Thoughts?

**Comment by mtibben** [comment]
So leave default at aws-vault for upcoming v5 (with option and env var for login?), and switch to login for v6?  We probably want to think about migrating creds between the keychains in v6 also

**Comment by lox** [comment]
Yeah I think so @mtibben. We'll add a `copy` command in 5.1 that will prepare for that too.

**Pull request closed without merging**
