### PR TITLE
Add support for the kwallet keyring

### PR DESCRIPTION
**Pull request by Vektah**
Adds support for the KDE wallet. CLI/Gnome would require their own backends.

When first creating the wallet it will prompt for a new password:
new-wallet

If the wallet is not open it will prompt for the password:
open-wallet

Unlike the OSX keyring the KDE wallet 'entries' are purely key value stores. To fit the entire Item I added a second layer of json encoding.

I'm not sure of the best way to automatically test this. I guess I could stub the dbus connection or the wrapper?

see https://github.com/99designs/aws-vault/issues/23

### CODE REVIEW

**Comment by lox** [comment]
Nice one @Vektah, Godeps need updating.

**Comment by lox** [comment]
Mind rebasing master and updating Godeps?

**Comment by lox** [comment]
So just to clarify, Kwallet doesn't have libsecret support? That would be the vastly better option IMO:
https://developer.gnome.org/libsecret/unstable/

**Comment by Vektah** [comment]
I've rebased and added godeps. The gitignore for vendor threw me off.

https://github.com/tmc/keyring/blob/master/keyring_linux.go uses the libsecret dbus api via `org.freedesktop.Secret.Service` but it didn't prompt for a wallet password at all and ended up being stored somewhere else.

**Pull request merged**
